Front

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -91,105 +91,6 @@ jobs:
           short-sha: ${{ needs.changes.outputs.short_sha }}
           changed-directories: ${{ needs.changes.outputs.changed_directories }}
 
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v1
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ env.AWS_REGION }}
-
-      # - name: Login to Amazon ECR
-      #   id: login-ecr
-      #   uses: aws-actions/amazon-ecr-login@v1
-
-      # - name: Substitute proxy env variables
-      #   run: envsubst <  default.conf.tpl > default.conf
-      #   working-directory: "${{ env.BACKEND_DIRECTORY }}/${{ env.PROXY_DIRECTORY }}/"
-      #   if: contains(needs.changes.outputs.changed_directories, 'proxy')
-
-      # - name: Substitute app env variables
-      #   run: envsubst <  server.js.tpl > server.js
-      #   working-directory: "${{ env.BACKEND_DIRECTORY }}/${{ env.NODEJS_DIRECTORY }}/"
-      #   if: contains(needs.changes.outputs.changed_directories, 'nodejs')
-
-      # - name: Build image for proxy...
-      #   uses: docker/build-push-action@v2
-      #   with:
-      #     context: "${{ env.BACKEND_DIRECTORY }}/${{ env.PROXY_DIRECTORY }}/"
-      #     file: "${{ env.BACKEND_DIRECTORY }}/${{ env.PROXY_DIRECTORY }}/Dockerfile"
-      #     push: true
-      #     tags: |
-      #       ${{ env.BACKEND_PROXY_REPOSITORY_URL }}:latest
-      #       ${{ env.BACKEND_PROXY_REPOSITORY_URL }}:${{ github.ref_name }}
-      #       ${{ env.BACKEND_PROXY_REPOSITORY_URL }}:${{ needs.changes.outputs.short_sha }}
-      #   env:
-      #     BACKEND_PROXY_REPOSITORY_URL: ${{ format('{0}/{1}', env.ECR_REPOSITORY_URL, env.BACKEND_PROXY_REPOSITORY_NAME) }}
-      #   if: contains(needs.changes.outputs.changed_directories, 'proxy')
-
-      # - name: Build image for backend...
-      #   uses: docker/build-push-action@v2
-      #   with:
-      #     context: "${{ env.BACKEND_DIRECTORY}}/${{ env.NODEJS_DIRECTORY }}/"
-      #     file: "${{ env.BACKEND_DIRECTORY}}/${{ env.NODEJS_DIRECTORY }}/Dockerfile"
-      #     push: true
-      #     tags: |
-      #       ${{ env.BACKEND_REPOSITORY_URL }}:latest
-      #       ${{ env.BACKEND_REPOSITORY_URL }}:${{ github.ref_name }}
-      #       ${{ env.BACKEND_REPOSITORY_URL }}:${{ needs.changes.outputs.short_sha }}
-      #   env:
-      #     BACKEND_REPOSITORY_URL: ${{ format('{0}/{1}', env.ECR_REPOSITORY_URL, env.BACKEND_REPOSITORY_NAME) }}
-      #   if: contains(needs.changes.outputs.changed_directories, 'nodejs')
-
-      # - name: Set proxy tag
-      #   uses: ./.github/actions/set-backend-tags/
-      #   with: 
-      #     short-sha: ${{ needs.changes.outputs.short_sha }}
-      #     repository-name: ${{ env.BACKEND_PROXY_REPOSITORY_NAME }}
-      #     filter-tag: ${{ env.FILTER_TAG }}
-      #     region: ${{ env.AWS_REGION }}
-      #     branch: ${{ github.ref_name }}
-      #     changed: ${{ contains(needs.changes.outputs.changed_directories, 'proxy') }}
-      #     tf-var-name: backend_proxy_container_image_tag
-
-      # - name: Set app tag
-      #   uses: ./.github/actions/set-backend-tags/
-      #   with: 
-      #     short-sha: ${{ needs.changes.outputs.short_sha }}
-      #     repository-name: ${{ env.BACKEND_REPOSITORY_NAME }}
-      #     filter-tag: ${{ env.FILTER_TAG }}
-      #     region: ${{ env.AWS_REGION }}
-      #     branch: ${{ github.ref_name }}
-      #     changed: ${{ contains(needs.changes.outputs.changed_directories, 'nodejs') }}
-      #     tf-var-name: backend_app_container_image_tag
-
-      # - name: Setup terraform 
-      #   uses: hashicorp/setup-terraform@v2
-      #   with:
-      #     terraform_wrapper: false
-
-      # - name: Terraform init
-      #   run: terraform init
-      #   working-directory: "${{ env.INFRASTRUCTURE_DIRECTORY }}/environments/dev/"
-
-      # - name: Terraform validate
-      #   id: validate
-      #   run: terraform validate -no-color
-      #   working-directory: "${{ env.INFRASTRUCTURE_DIRECTORY }}/environments/dev/"
-
-      # - name: Terraform plan
-      #   run: terraform plan -no-color
-      #   env:
-      #       TF_VAR_backend_app_container_port: ${{ env.APP_PORT }}
-      #       TF_VAR_backend_proxy_container_port: ${{ env.PROXY_PORT }}       
-      #   working-directory: "${{ env.INFRASTRUCTURE_DIRECTORY }}/environments/dev/"
-
-      # # - name: Terraform apply
-      # #   run: terraform apply -auto-approve -target module.ecs.aws_ecs_service.api -target module.ecs.aws_ecs_task_definition.api
-      # #   env:
-      # #       TF_VAR_backend_app_container_port: ${{ env.APP_PORT }}
-      # #       TF_VAR_backend_proxy_container_port: ${{ env.PROXY_PORT }}       
-      # #   working-directory: "${{ env.INFRASTRUCTURE_DIRECTORY }}/environments/dev/"
-
   frontend:
     name: Frontend
     needs: [changes, infrastructure, backend]
@@ -209,72 +110,81 @@ jobs:
         with:
           fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
 
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v1
-        with:
-          node-version: 16.x
-
-      - name: Install dependencies
-        run: npm ci
-        working-directory: ${{ env.FRONTEND_DIRECTORY }}
-      
-      - name: Test
-        run: npm test
-        env:
-          CI: true
-        working-directory: ${{ env.FRONTEND_DIRECTORY }}
-      
-      - name: Generate build
-        run: npm run build
-        working-directory: ${{ env.FRONTEND_DIRECTORY }}
-
-      - name: "Check if index.html exists..."
-        id: check_files
-        uses: andstor/file-existence-action@v1
-        with:
-          files: "./${{env.FRONTEND_DIRECTORY}}/build/index.html"
-
-      - name: "Fail if files dont exit"
-        if: steps.check_files.outputs.files_exists != 'true'
-        run: |
-          ls -alh ./build
-          echo "./$FRONTEND_DIRECTORY/build/index.html is missing!"
-          exit 1
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+      - name: Frontend
+        id: frontend
+        uses: ./.github/actions/front
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+          short-sha: ${{ needs.changes.outputs.short_sha }}
+          changed-directories: ${{ needs.changes.outputs.changed_directories }}
 
-      - name: Deploy to S3
-        run: aws s3 sync "./build/" s3://artifacts1910 --dryrun --exclude docker --delete
-        working-directory: ${{ env.FRONTEND_DIRECTORY }}
+      # - name: Use Node.js 16.x
+      #   uses: actions/setup-node@v1
+      #   with:
+      #     node-version: 16.x
 
-      - name: Setup terraform 
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_wrapper: false
+      # - name: Install dependencies
+      #   run: npm ci
+      #   working-directory: ${{ env.FRONTEND_DIRECTORY }}
+      
+      # - name: Test
+      #   run: npm test
+      #   env:
+      #     CI: true
+      #   working-directory: ${{ env.FRONTEND_DIRECTORY }}
+      
+      # - name: Generate build
+      #   run: npm run build
+      #   working-directory: ${{ env.FRONTEND_DIRECTORY }}
 
-      - name: Terraform Init
-        run: terraform init
-        working-directory: "./tier0/environments/dev/"
+      # - name: "Check if index.html exists..."
+      #   id: check_files
+      #   uses: andstor/file-existence-action@v1
+      #   with:
+      #     files: "./${{env.FRONTEND_DIRECTORY}}/build/index.html"
+
+      # - name: "Fail if files dont exit"
+      #   if: steps.check_files.outputs.files_exists != 'true'
+      #   run: |
+      #     ls -alh ./build
+      #     echo "./$FRONTEND_DIRECTORY/build/index.html is missing!"
+      #     exit 1
+
+      # - name: Configure AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{ env.AWS_REGION }}
+
+      # - name: Deploy to S3
+      #   run: aws s3 sync "./build/" s3://artifacts1910 --dryrun --exclude docker --delete
+      #   working-directory: ${{ env.FRONTEND_DIRECTORY }}
+
+      # - name: Setup terraform 
+      #   uses: hashicorp/setup-terraform@v2
+      #   with:
+      #     terraform_wrapper: false
+
+      # - name: Terraform Init
+      #   run: terraform init
+      #   working-directory: "./tier0/environments/dev/"
     
-      - name: Call terraform output
-        run: |
-          echo "CLOUDFRONT_ID=$(terraform output cloudfront_id | tr -d '\"')" >> "$GITHUB_ENV"
-        working-directory: "./tier0/environments/dev/"
+      # - name: Call terraform output
+      #   run: |
+      #     echo "CLOUDFRONT_ID=$(terraform output cloudfront_id | tr -d '\"')" >> "$GITHUB_ENV"
+      #   working-directory: "./tier0/environments/dev/"
 
-      - name: Test
-        run: echo ${{ env.CLOUDFRONT_ID }}
+      # - name: Test
+      #   run: echo ${{ env.CLOUDFRONT_ID }}
 
-      - name: Invalidate Cache
-        uses: chetan/invalidate-cloudfront-action@v2
-        env:
-          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
-          PATHS: "/*"
-          AWS_REGION: ${{ env.AWS_REGION }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          DEBUG: "1"
+      # - name: Invalidate Cache
+      #   uses: chetan/invalidate-cloudfront-action@v2
+      #   env:
+      #     DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
+      #     PATHS: "/*"
+      #     AWS_REGION: ${{ env.AWS_REGION }}
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     DEBUG: "1"
